INSERT INTO LABORATORIO(NOME) VALUES('Teuto');

INSERT INTO GRUPO_MEDICAMENTO(NOME) VALUES('Azitromicina');
INSERT INTO GRUPO_MEDICAMENTO(NOME) VALUES('Aciclovir');

INSERT INTO MEDICAMENTO(NOME, GRUPO_MEDICAMENTO_ID, LABORATORIO_ID) VALUES('Med 1', 1, 1);
INSERT INTO MEDICAMENTO(NOME, GRUPO_MEDICAMENTO_ID, LABORATORIO_ID) VALUES('Med 2', 2, 1);